# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: goodreads-app:latest
        restart: unless-stopped
        container_name: koinz-app
        volumes:
            - './:/var/www'
        networks:
            - goodreads
        depends_on:
            - mysql
            - redis


    worker:
        image: goodreads-app:latest
        restart: unless-stopped
        volumes:
            - './:/var/www'
        networks:
            - goodreads
        depends_on:
            - app
            - mysql
            - redis
        command: php artisan queue:work -vvv --tries=3


    nginx:
        image: nginx:1.25.5
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - './:/var/www'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - goodreads
        depends_on:
            - mysql
            - app

    mysql:
        image: mysql:8.4.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'goodreads-mysql:/var/lib/mysql'
        networks:
            - goodreads


    redis:
        image: redis:7.2.4
        restart: unless-stopped
        networks:
            - goodreads

      
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     links:
    #         - mysql:mysql
    #     ports:
    #         - 8080:80
    #     environment:
    #         MYSQL_USERNAME: "${DB_USERNAME}"
    #         MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    #         PMA_HOST: mysql
    #     networks:
    #         - goodreads
    #     depends_on:
    #         - mysql

networks:
    goodreads:
        driver: bridge
volumes:
    goodreads-mysql:
        driver: local

